### ISSUE TITLE
Internal Server Error - The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by leiendeckerlu** [pinellolab/DrugThatGene#1]
Hi there, 

I tried to run DTG locally using docker, but after submission of my gene list I get the following error in the browser:

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This is the output of the docker run:

```
[2019-07-31 15:19:31 +0000] [8] [INFO] Handling signal: winch
[2019-07-31 15:19:31 +0000] [8] [INFO] Handling signal: winch
[2019-07-31 15:19:31 +0000] [8] [INFO] Handling signal: winch
[2019-07-31 15:19:31 +0000] [8] [INFO] Handling signal: winch
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET / HTTP/1.1" 200 5198 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET /static/style.css HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET /static/tableexport.min.css HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET /static/xlsx.core.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET /static/blob.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET /static/FileSaver.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET /static/tableexport.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET /static/bootbox.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:47 +0000] "GET /static/square_logo.png HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:49 +0000] "GET /static/manifest.json HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:19:49 +0000] "GET /static/favicon-32x32.png HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
[2019-07-31 15:20:58,965] ERROR in app: Exception on /submit [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 1366, in submit
    df_gene_list, df_gene_list_output, df_gene_list_hidden_table, df_gene_list_paths, df_gene_list_paths_output, df_gene_list_paths_hidden_table, df_gene_list_complexes, df_gene_list_complexes_output, df_gene_list_complexes_hidden_table = get_filled_dataframe(list_of_genes)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 208, in get_filled_dataframe
    OMIM_ID,ENS_ID,omim_main_links, omim_variants_links,exac_links,clinvar_links,gnomad_links,pharos_links=get_links_from_gene(gene_name)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 90, in get_links_from_gene
    if omim_has_variant(OMIM_ID):
  File "/DrugThatGene/DrugThatGene/__init__.py", line 63, in omim_has_variant
    json_data = json.loads(response.content)
  File "/opt/conda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
172.17.0.1 - - [31/Jul/2019:15:20:58 +0000] "POST /submit HTTP/1.1" 500 291 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:20:59 +0000] "GET /favicon.ico HTTP/1.1" 302 209 "http://localhost:9999/submit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:20:59 +0000] "GET / HTTP/1.1" 200 5198 "http://localhost:9999/submit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
[2019-07-31 15:21:31,238] ERROR in app: Exception on /submit [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 1366, in submit
    df_gene_list, df_gene_list_output, df_gene_list_hidden_table, df_gene_list_paths, df_gene_list_paths_output, df_gene_list_paths_hidden_table, df_gene_list_complexes, df_gene_list_complexes_output, df_gene_list_complexes_hidden_table = get_filled_dataframe(list_of_genes)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 208, in get_filled_dataframe
    OMIM_ID,ENS_ID,omim_main_links, omim_variants_links,exac_links,clinvar_links,gnomad_links,pharos_links=get_links_from_gene(gene_name)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 90, in get_links_from_gene
    if omim_has_variant(OMIM_ID):
  File "/DrugThatGene/DrugThatGene/__init__.py", line 63, in omim_has_variant
    json_data = json.loads(response.content)
  File "/opt/conda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
172.17.0.1 - - [31/Jul/2019:15:21:31 +0000] "POST /submit HTTP/1.1" 500 291 "http://localhost:9999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:21:31 +0000] "GET /favicon.ico HTTP/1.1" 302 209 "http://localhost:9999/submit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
172.17.0.1 - - [31/Jul/2019:15:21:31 +0000] "GET / HTTP/1.1" 200 5198 "http://localhost:9999/submit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
[2019-07-31 15:22:29 +0000] [8] [INFO] Handling signal: winch
```

**Comment by lucapinello** [comment]
Thanks for reporting this problem. I think I have fixed it.

Can you please try to pull the latest docker image with:

`docker pull pinellolab/drugthatgene
`
and try again?

Please let me know if this works for you so I can close this issue.

Thanks,

Luca

**Comment by leiendeckerlu** [comment]
Hi Luca,

very nice - that did the trick!

Thanks,

Lukas
