### ISSUE TITLE
Problems with repository installation

### ISSUE THREAD

**Issue by Chavez-Fumagalli** [pinellolab/DrugThatGene#3]
Hi,
I am getting some trouble to install the repository. I am following the instructions as in the DTG page. 
**#I am getting the following:**
sudo docker run -p 9999:9999 -it pinellolab/drugthatgene
Unable to find image 'pinellolab/drugthatgene:latest' locally
latest: Pulling from pinellolab/drugthatgene
c5e155d5a1d1: Pull complete 
6af5f265bf37: Pull complete 
766bd8e61980: Pull complete 
f08357b4bd10: Pull complete 
4b6196e8cb60: Pull complete 
94ac44c920c6: Pull complete 
d7f27a8a78d5: Pull complete 
9369b8e24f81: Pull complete 
667a1252f5f9: Pull complete 
Digest: sha256:217dec5cdc5466a7db5afff397a397d017a0b9b51ec68dae3a8d4d3ab3564da1
Status: Downloaded newer image for pinellolab/drugthatgene:latest
[2021-05-26 05:16:28 +0000] [8] [INFO] Starting gunicorn 19.10.0
[2021-05-26 05:16:28 +0000] [8] [INFO] Listening at: http://0.0.0.0:9999 (8)
[2021-05-26 05:16:28 +0000] [8] [INFO] Using worker: sync
[2021-05-26 05:16:28 +0000] [12] [INFO] Booting worker with pid: 12
[2021-05-26 05:16:28 +0000] [13] [INFO] Booting worker with pid: 13
/opt/conda/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py:52: DtypeWarning: Columns (38,45) have mixed types. Specify dtype option on import or set low_memory=False.
  return self.load_wsgiapp()
/opt/conda/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py:52: DtypeWarning: Columns (38,45) have mixed types. Specify dtype option on import or set low_memory=False.
  return self.load_wsgiapp()
**#Before this I try to get to the DTG page, type some genes and as a result I get :"Internal server error"; and when I came back to terminal it appears to me:**
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET / HTTP/1.1" 200 5201 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET /static/style.css HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET /static/blob.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET /static/FileSaver.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET /static/tableexport.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET /static/bootbox.min.js HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET /static/tableexport.min.css HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET /static/square_logo.png HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:19:58 +0000] "GET /static/favicon-16x16.png HTTP/1.1" 200 0 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The API key: &#39;jrnmZyB4QS6R5ANxZGswmA&#39;, is inactive, please contact us at https:&#47;&#47;omim.org&#47;contact if this is an issue.</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/9.0.35</h3></body></html>
[2021-05-26 05:20:20,283] ERROR in app: Exception on /submit [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 1373, in submit
    df_gene_list, df_gene_list_output, df_gene_list_hidden_table, df_gene_list_paths, df_gene_list_paths_output, df_gene_list_paths_hidden_table, df_gene_list_complexes, df_gene_list_complexes_output, df_gene_list_complexes_hidden_table = get_filled_dataframe(list_of_genes)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 215, in get_filled_dataframe
    OMIM_ID,ENS_ID,omim_main_links, omim_variants_links,exac_links,clinvar_links,gnomad_links,pharos_links=get_links_from_gene(gene_name)
  File "/DrugThatGene/DrugThatGene/__init__.py", line 97, in get_links_from_gene
    if omim_has_variant(OMIM_ID):
  File "/DrugThatGene/DrugThatGene/__init__.py", line 72, in omim_has_variant
    if json_data:
UnboundLocalError: local variable 'json_data' referenced before assignment
172.17.0.1 - - [26/May/2021:05:20:20 +0000] "POST /submit HTTP/1.1" 500 290 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
172.17.0.1 - - [26/May/2021:05:20:20 +0000] "GET /favicon.ico HTTP/1.1" 302 209 "http://localhost:9999/submit" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"

Please, can you point the error?
Thanks for your help.

Best
Miguel

**Comment by lucapinello** [comment]
Hi Miguel,

The problem is due to an expired OMIM key. Unfortunately I learned that I am not allowed to distribute a key, so you need to obtain one and replace this line:

https://github.com/pinellolab/DrugThatGene/blob/890f271462659ec2e17926651228197f518f17b4/DrugThatGene/__init__.py#L22

See instructions here: https://www.omim.org/api

After this just rebuild the docker image and the website should start.
